texto="Universidad Tecnologica de León"
print(type(texto))
print(texto.lower())
print(texto.upper())
print(texto.title())
print(texto.find("de"))
print(texto.count("a"))
texto2=texto.replace("e","3")
texto3=texto.split(" ")
print(texto3)
